/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaassignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AddCust extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public AddCust() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        custName = new javax.swing.JLabel();
        custBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emailBox = new javax.swing.JTextField();
        icNo = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        icBox = new javax.swing.JTextField();
        contactBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setInheritsPopupMenu(true);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("< Back");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setText("Add Customer Record");

        custName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        custName.setText("Customer Name");

        custBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        custBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custBoxFocusLost(evt);
            }
        });
        custBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custBoxActionPerformed(evt);
            }
        });
        custBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                custBoxKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Email Address");

        emailBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        emailBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailBoxFocusLost(evt);
            }
        });
        emailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBoxActionPerformed(evt);
            }
        });
        emailBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailBoxKeyTyped(evt);
            }
        });

        icNo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        icNo.setText("Identity Card No");

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Contact Number");

        icBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        icBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                icBoxFocusLost(evt);
            }
        });
        icBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icBoxActionPerformed(evt);
            }
        });
        icBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                icBoxKeyTyped(evt);
            }
        });

        contactBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        contactBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                contactBoxFocusLost(evt);
            }
        });
        contactBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactBoxActionPerformed(evt);
            }
        });
        contactBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contactBoxKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("*");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("*");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("*");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(custName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contactBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(157, 157, 157)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 0, 0)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(icNo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icBox, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(401, 401, 401)
                        .addComponent(jLabel1)))
                .addGap(0, 153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(custName)
                                    .addComponent(custBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel4)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(icNo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(contactBox, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel7)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Homepage homeBooking = new Homepage();
        homeBooking.show();
        dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void custBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custBoxFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_custBoxFocusLost

    private void custBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_custBoxActionPerformed

    private void emailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBoxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_emailBoxActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        // Initialise string array to store data

        String[] custData = new String[5];
        
        // ID Counter
        File readFile = new File("customer.txt");
        String lastLine = "";
        int newID;
        String[] lastLineArray = new String[4];
        try {
            Scanner s = new Scanner(readFile);
            while (s.hasNextLine()) {
                lastLine = s.nextLine();
            }
            lastLineArray = lastLine.split("\t");
            newID = Integer.parseInt(lastLineArray[0]) + 1;
            custData[0] = String.valueOf(newID);
        } 
        catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex);
        }

        
        // Customer Name
        custData[1] = custBox.getText();
        if (custData[1] == null || custData[1].equals("")) {
            JOptionPane.showMessageDialog(null, "Customer Name cannot leave empty");
            return;
        }

        // Email
        custData[2] = emailBox.getText();
        if (custData[2] == null || custData[2].equals("")) {
            JOptionPane.showMessageDialog(null, "Email Address cannot leave empty");
            return;
        }

        // Telephone
        custData[3] = contactBox.getText();
        if (custData[3] == null || custData[3].equals("")) {
            JOptionPane.showMessageDialog(null, "Contact Number cannot leave empty");
            return;
        }
        else if (custData[3].length() < 10) {
            JOptionPane.showMessageDialog(null, "Invalid Phone Number Length");
            return;
        }
        

        // IC
         custData[4] = icBox.getText();
        if (custData[4] == null || custData[4].equals("")) {
            JOptionPane.showMessageDialog(null, "Identity card cannot leave empty");
            return;
        }
        else if (custData[4].length() != 12) {
            JOptionPane.showMessageDialog(null, "Invalid IC No Length");
            return;
        }
       
        // Append data into text file
        try {
            PrintWriter pw = new PrintWriter(new FileOutputStream(new File("customer.txt"), true));
            pw.append("\n");
            for (int i = 0; i < 5; i++) {
                if (i != 0) {
                    pw.append("\t");
                }
                pw.append(custData[i]);
            }

            pw.close();
            JOptionPane.showMessageDialog(null, "Record Added!");

            // Redirect back to homepage
            Homepage home = new Homepage();
            home.show();
            dispose();

        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        // TODO add your handling code here:
        custBox.setText(null);
        contactBox.setText(null);
        emailBox.setText(null);
        icBox.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed

    private void icBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icBoxActionPerformed

    }//GEN-LAST:event_icBoxActionPerformed

    private void contactBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactBoxFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_contactBoxFocusLost

    private void contactBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactBoxActionPerformed

    private void emailBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailBoxFocusLost
        // TODO add your handling code here:
        String emailInput = emailBox.getText();
        if (!(emailInput.contains("@") && emailInput.contains(".com"))) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address");
            emailBox.setText(null);
        }
    }//GEN-LAST:event_emailBoxFocusLost

    private void icBoxFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_icBoxFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_icBoxFocusLost

    private void custBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custBoxKeyTyped
        // TODO add your handling code here:
        char nameInput = evt.getKeyChar();
        // ISO Control is for Backspace and Delete
        // Reference: https://www.youtube.com/watch?v=C6x_TgJH444;
        if(Character.isLetter(nameInput) || Character.isWhitespace(nameInput) || Character.isISOControl(nameInput)) {
            return;
        }
        else {
            JOptionPane.showMessageDialog(null, "Customer name cannot have special character or number");
            String currentLine = custBox.getText();
            custBox.setText(currentLine.substring(0,-1));
        }
    }//GEN-LAST:event_custBoxKeyTyped

    private void icBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icBoxKeyTyped
        // TODO add your handling code here:
        String icInput = icBox.getText();
        char c3 = evt.getKeyChar();
        if(Character.isDigit(c3) || Character.isISOControl(c3)) {
            if (Character.isISOControl(c3)) {
                return;
            }
            else if (icInput.length() > 11) {
                JOptionPane.showMessageDialog(null, "Invalid IC No Length");
                icBox.setText(icInput.substring(0, -1));
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "IC number only accept numeric");
            icBox.setText(icInput.substring(0, -1));
        }
    }//GEN-LAST:event_icBoxKeyTyped

    private void contactBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contactBoxKeyTyped
        // TODO add your handling code here:
        String phoneInput = contactBox.getText();
        char c2 = evt.getKeyChar();
        if(Character.isDigit(c2) || Character.isISOControl(c2)) {
            if (Character.isISOControl(c2)) {
                return;
            }
            else if (phoneInput.length() > 10) {
                JOptionPane.showMessageDialog(null, "Invalid Phone Length");
                contactBox.setText(phoneInput.substring(0, -1));
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Phone number only accept numeric");
            contactBox.setText(phoneInput.substring(0, -1));
        }
    }//GEN-LAST:event_contactBoxKeyTyped

    private void emailBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_emailBoxKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCust().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactBox;
    private javax.swing.JTextField custBox;
    private javax.swing.JLabel custName;
    private javax.swing.JTextField emailBox;
    private javax.swing.JTextField icBox;
    private javax.swing.JLabel icNo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
