/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaassignment;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ModifyCust extends javax.swing.JFrame {

    /**
     * Creates new form ModifyCust
     */
    String[] inputData;
    public ModifyCust(String[] rowData) {
        initComponents();
        this.inputData = rowData;
        
        custNameEdit.setText(inputData[1]);
        emailBoxEdit.setText(inputData[2]);
        phoneBoxEdit.setText(inputData[3]);
        icEditCust.setText(inputData[4]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        custNameField = new javax.swing.JLabel();
        custNameEdit = new javax.swing.JTextField();
        phoneField = new javax.swing.JLabel();
        phoneBoxEdit = new javax.swing.JTextField();
        saveBtn = new javax.swing.JButton();
        resetBookingForm = new javax.swing.JButton();
        emailEdit = new javax.swing.JLabel();
        emailBoxEdit = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        icEditCust = new javax.swing.JTextField();
        icField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setInheritsPopupMenu(true);

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("< Back");
        jButton7.setOpaque(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel46.setText("Edit Customer  Record");

        custNameField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        custNameField.setText("Customer Name");

        custNameEdit.setEditable(false);
        custNameEdit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        custNameEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custNameEditFocusLost(evt);
            }
        });
        custNameEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custNameEditActionPerformed(evt);
            }
        });
        custNameEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                custNameEditKeyTyped(evt);
            }
        });

        phoneField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        phoneField.setText("Contact Number");

        phoneBoxEdit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        phoneBoxEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneBoxEditFocusLost(evt);
            }
        });
        phoneBoxEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneBoxEditActionPerformed(evt);
            }
        });
        phoneBoxEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneBoxEditKeyTyped(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        resetBookingForm.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        resetBookingForm.setText("Reset");
        resetBookingForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBookingFormActionPerformed(evt);
            }
        });

        emailEdit.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailEdit.setText("Email Address");

        emailBoxEdit.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        emailBoxEdit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailBoxEditFocusLost(evt);
            }
        });
        emailBoxEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailBoxEditActionPerformed(evt);
            }
        });

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 51, 51));
        jLabel54.setText("*");

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel55.setForeground(new java.awt.Color(255, 51, 51));
        jLabel55.setText("*");

        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(255, 51, 51));
        jLabel58.setText("*");

        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(255, 51, 51));
        jLabel59.setText("*");

        icEditCust.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        icEditCust.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                icEditCustFocusLost(evt);
            }
        });
        icEditCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icEditCustActionPerformed(evt);
            }
        });
        icEditCust.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                icEditCustKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                icEditCustKeyTyped(evt);
            }
        });

        icField.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        icField.setText("Identity Card No");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(112, 112, 112)
                                        .addComponent(custNameField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel54))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(phoneField)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel55)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(custNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(phoneBoxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(icField)
                                    .addComponent(emailEdit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel59)
                                    .addComponent(jLabel58))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailBoxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(icEditCust, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(resetBookingForm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton7)
                        .addGap(383, 383, 383)
                        .addComponent(jLabel46)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(49, 49, 49))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(custNameField)
                            .addComponent(custNameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailEdit)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel54))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel58)
                            .addComponent(emailBoxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(127, 127, 127)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel59)
                        .addComponent(icEditCust, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel55)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(phoneBoxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(icField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetBookingForm, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1175, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 594, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Booking book1 = new Booking();
        book1.show();
        dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void custNameEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameEditFocusLost

    }//GEN-LAST:event_custNameEditFocusLost

    private void custNameEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custNameEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameEditActionPerformed

    private void custNameEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_custNameEditKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_custNameEditKeyTyped

    private void phoneBoxEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneBoxEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneBoxEditActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // Initialise string array to store data
        String[] bookingData = new String[5];
        // Customer ID
        bookingData[0] = inputData[0];

        // Customer Name
        bookingData[1] = inputData[1];

        // Email Address
        bookingData[2] = emailBoxEdit.getText();
        System.out.println(bookingData[2]);
        if (bookingData[2] == null || bookingData[2] == "") {
            JOptionPane.showMessageDialog(null, "Email Address cannot leave empty");
            return;
        }

        // Contact Number
        bookingData[3] = phoneBoxEdit.getText();
        if (bookingData[3] == null || bookingData[3] == "") {
            JOptionPane.showMessageDialog(null, "Contact Number cannot leave empty");
            return;
        }
        // Identity Card No
        bookingData[4] = icEditCust.getText();
        if (bookingData[4] == null || bookingData[4] == "") {
            JOptionPane.showMessageDialog(null, "IC Number cannot leave empty");
            return;
        }

        // Copy all file content to arraylist
        File tmp = new File("customer.txt");
        int lineCounter = 0;
        try {
            Scanner countLine = new Scanner(tmp);
            while(countLine.hasNextLine()) {
                countLine.nextLine();
                lineCounter++;
            }
            countLine.close();
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e);
        }
        String[][] fileContent = new String[lineCounter][6];

        String line;
        String[] lineArray;
        int counter = 0;
        try {
            Scanner read = new Scanner(tmp);
            while(read.hasNextLine()) {
                line = read.nextLine();
                lineArray = line.split("\t");
//                System.out.println(lineArray[0] + " " + inputData[0]);
                if ((lineArray[0].equals(inputData[0]))) {
                    fileContent[counter] = bookingData;
//                    System.out.println("yeet");
                    counter++;
                    continue;
                }
                fileContent[counter] = lineArray;
                counter++;
            }
            read.close();
        }
        catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Error" + ex);
        }

        // Append data into text file
        try {
            File delete = new File("customer.txt");
            delete.delete();
            PrintWriter pw = new PrintWriter("customer.txt");
            for (int i = 0; i < fileContent.length; i++) {
                if (i != 0) {
                    pw.append("\n");
                }
                for (String lines:fileContent[i]) {
                    pw.append(lines);

                    pw.append("\t");
//                    System.out.println(lines);
                }
            }
            pw.close();

            JOptionPane.showMessageDialog(null, "Update Success!");
            //
            // Redirect back to homepage
            Booking book = new Booking();
            book.show();
            dispose();
            //
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void resetBookingFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBookingFormActionPerformed
        // TODO add your handling code here:
        custNameEdit.setText(inputData[1]);
        emailBoxEdit.setText(inputData[2]);
        phoneBoxEdit.setText(inputData[3]);
        icEditCust.setText(inputData[4]);
    }//GEN-LAST:event_resetBookingFormActionPerformed

    private void emailBoxEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailBoxEditActionPerformed

    }//GEN-LAST:event_emailBoxEditActionPerformed

    private void icEditCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icEditCustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icEditCustActionPerformed

    private void emailBoxEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailBoxEditFocusLost
        // TODO add your handling code here:
        String emailInput = emailBoxEdit.getText();
        if (!(emailInput.contains("@") && emailInput.contains(".com"))) {
            JOptionPane.showMessageDialog(null, "Invalid Email Address");
            emailBoxEdit.setText(inputData[2]);
        }
    }//GEN-LAST:event_emailBoxEditFocusLost

    private void phoneBoxEditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneBoxEditKeyTyped
        // TODO add your handling code here:
        String phoneInput = phoneBoxEdit.getText();
        char c2 = evt.getKeyChar();
        if(Character.isDigit(c2) || Character.isISOControl(c2)) {
            if (Character.isISOControl(c2)) {
                return;
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Phone number only accept numeric");
            phoneBoxEdit.setText(phoneInput.substring(0, -1));
        }
    }//GEN-LAST:event_phoneBoxEditKeyTyped

    private void icEditCustKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icEditCustKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_icEditCustKeyReleased

    private void icEditCustKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_icEditCustKeyTyped
        // TODO add your handling code here:
        String icInput = icEditCust.getText();
        char c2 = evt.getKeyChar();
        if(Character.isDigit(c2) || Character.isISOControl(c2)) {
            if (Character.isISOControl(c2)) {
                return;
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "IC No only accept numeric");
            phoneBoxEdit.setText(icInput.substring(0, -1));
        }
    }//GEN-LAST:event_icEditCustKeyTyped

    private void icEditCustFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_icEditCustFocusLost
        // TODO add your handling code here:
        String icInput = icEditCust.getText();
        if ((icInput.length()) != 12) {
          JOptionPane.showMessageDialog(null, "Invalid IC No Length");
          icEditCust.setText(inputData[4]);
        }
    }//GEN-LAST:event_icEditCustFocusLost

    private void phoneBoxEditFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneBoxEditFocusLost
        // TODO add your handling code here:
        String phoneInputs = phoneBoxEdit.getText();
        if ((phoneInputs.length()) < 10 || phoneInputs.length() > 11) {
            JOptionPane.showMessageDialog(null, "Invalid Contact Number Length");
            phoneBoxEdit.setText(inputData[3]);
        }
    }//GEN-LAST:event_phoneBoxEditFocusLost

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ModifyCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ModifyCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ModifyCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ModifyCust.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ModifyCust().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField custNameEdit;
    private javax.swing.JLabel custNameField;
    private javax.swing.JTextField emailBoxEdit;
    private javax.swing.JLabel emailEdit;
    private javax.swing.JTextField icEditCust;
    private javax.swing.JLabel icField;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField phoneBoxEdit;
    private javax.swing.JLabel phoneField;
    private javax.swing.JButton resetBookingForm;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
