/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.javaassignment;

import java.io.File;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Scanner;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class ReceiptPage extends javax.swing.JFrame {

    /**
     * Creates new form ReceiptPage
     */
    String[] inputData1;
    public ReceiptPage(String[] rowData) {
        initComponents();
        inputData1 = rowData;
        
        // User data
        String userID = inputData1[0];
        String usernames = "", email = "", contact = "";
        File user = new File("customer.txt");
        try {
            String line;
            String[] lineArray;
            Scanner userScan = new Scanner(user);
            while(userScan.hasNextLine()) {
                line = userScan.nextLine();
                lineArray = line.split("\t");
                
                if (lineArray[0].equals(inputData1[0])) {
                    usernames = lineArray[1];
                    email = lineArray[2];
                    contact = lineArray[3];
                    break;
                }
            }
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Errors:" + e);
        }
        
        // Date
        String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date());
        String checkIn = inputData1[3];
        String checkOut = inputData1[4];
         
        // Description
        String description = inputData1[1] + " ( " + inputData1[2] + " )";
        
        Date dateCheckIn, dateCheckOut;
        long diffs = 0;
        try {
            // Price
            dateCheckIn =new SimpleDateFormat("yyyy-MM-dd").parse(checkIn);
            dateCheckOut = new SimpleDateFormat("yyyy-MM-dd").parse(checkOut);
            
            long diffMillies = Math.abs(dateCheckIn.getTime() - dateCheckOut.getTime());
            diffs = TimeUnit.DAYS.convert(diffMillies, TimeUnit.MILLISECONDS);
        } 
        catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Errorss:" + ex);
        }
        DecimalFormat df = new DecimalFormat("0.00");
        double priceWithoutTax = diffs * 350.00;
        double tourismTax = diffs * 10.00;
        double serviceTax = priceWithoutTax * 10 / 100;
        double total = priceWithoutTax + tourismTax + serviceTax;
        
        String sTotal = df.format(total);
        String sPriceWithoutTax = df.format(priceWithoutTax);
        String sTourismTax = df.format(tourismTax);
        String sServiceTax = df.format(serviceTax);
//System.out.println(total);

        // Set data into textbox
        username.setText(usernames);
        userContact.setText(contact);
        userEmail.setText(email);
        todayDate.setText(today);
        checkInDateReceipt.setText(checkIn);
        checkOutDateReceipt.setText(checkOut);
        RoomTypeField.setText(description);
        Price.setText(sPriceWithoutTax);
        ServiceTax.setText(sServiceTax);
        TourismTax.setText(sTourismTax);
        TotalPrice.setText(sTotal);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backReceipt = new javax.swing.JButton();
        ReceiptPanel = new javax.swing.JPanel();
        ReceiptTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        checkInDateReceipt = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        checkOutDateReceipt = new javax.swing.JLabel();
        RoomTypeField = new javax.swing.JLabel();
        checkInDateReceipt3 = new javax.swing.JLabel();
        Price = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ServiceTax = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        TourismTax = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TotalPrice = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        userContact = new javax.swing.JLabel();
        todayDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        backReceipt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        backReceipt.setText("< Back");
        backReceipt.setOpaque(false);
        backReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backReceiptActionPerformed(evt);
            }
        });

        ReceiptPanel.setBackground(new java.awt.Color(255, 255, 255));

        ReceiptTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        ReceiptTitle.setText("Receipt");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel1.setText("Guest Name ");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setText("Contact Number");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Email Address");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("Billing Information");

        jLabel4.setText("________________________________________________________________________________________________________________________________________________________________________");

        jLabel6.setText("________________________________________________________________________________________________________________________________________________________________________");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Check-Out-Date");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("Description");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("Quantity");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Amount (RM)");

        checkInDateReceipt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        checkInDateReceipt.setText("2022/04/22");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("Check-In-Date");

        checkOutDateReceipt.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        checkOutDateReceipt.setText("2022/04/22");

        RoomTypeField.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        RoomTypeField.setText("Seaview (S01)");

        checkInDateReceipt3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        checkInDateReceipt3.setText("1");

        Price.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        Price.setText("1200.00");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        jLabel11.setText("Tourism Tax :");

        ServiceTax.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        ServiceTax.setText("20.00");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        jLabel14.setText("Service Tax (10%) :");

        jLabel15.setText("________________________________________________________________________________________________________________________________________________________________________");

        TourismTax.setFont(new java.awt.Font("Tw Cen MT", 0, 15)); // NOI18N
        TourismTax.setText("10.00");

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        jLabel17.setText("Total Charged :");

        TotalPrice.setFont(new java.awt.Font("Tw Cen MT", 1, 15)); // NOI18N
        TotalPrice.setText("1500.00");

        jLabel19.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel19.setText("~ Thanks for choosing Sunshine Resort ~");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel18.setText(":");

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText(":");

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel21.setText(":");

        userEmail.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        userEmail.setText("ali@gmail.com");

        username.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        username.setText("Ali");

        userContact.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        userContact.setText("01112345678");

        todayDate.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        todayDate.setText("2022/04/22");

        javax.swing.GroupLayout ReceiptPanelLayout = new javax.swing.GroupLayout(ReceiptPanel);
        ReceiptPanel.setLayout(ReceiptPanelLayout);
        ReceiptPanelLayout.setHorizontalGroup(
            ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ReceiptPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel7)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel8)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(35, 35, 35))
                            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                .addComponent(checkInDateReceipt)
                                .addGap(100, 100, 100)
                                .addComponent(checkOutDateReceipt)
                                .addGap(166, 166, 166)
                                .addComponent(RoomTypeField)
                                .addGap(122, 122, 122)
                                .addComponent(checkInDateReceipt3))
                            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(todayDate))
                                    .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(userContact, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(ReceiptPanelLayout.createSequentialGroup()
                        .addGap(0, 31, Short.MAX_VALUE)
                        .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReceiptPanelLayout.createSequentialGroup()
                                            .addComponent(ServiceTax, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReceiptPanelLayout.createSequentialGroup()
                                            .addComponent(TourismTax, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12))))))))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReceiptPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReceiptPanelLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(ReceiptTitle))
                    .addGroup(ReceiptPanelLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ReceiptPanelLayout.setVerticalGroup(
            ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReceiptPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(ReceiptTitle)
                .addGap(27, 27, 27)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel20)
                    .addComponent(userContact, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel21)
                    .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(todayDate))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkInDateReceipt)
                    .addComponent(checkOutDateReceipt)
                    .addComponent(RoomTypeField)
                    .addComponent(checkInDateReceipt3)
                    .addComponent(Price))
                .addGap(33, 33, 33)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceTax)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TourismTax))
                .addGap(3, 3, 3)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReceiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TotalPrice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backReceipt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(ReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(backReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ReceiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backReceiptActionPerformed
        // TODO add your handling code here:
        Booking book2 = new Booking();
        book2.show();
        dispose();
    }//GEN-LAST:event_backReceiptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReceiptPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ReceiptPage().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Price;
    private javax.swing.JPanel ReceiptPanel;
    private javax.swing.JLabel ReceiptTitle;
    private javax.swing.JLabel RoomTypeField;
    private javax.swing.JLabel ServiceTax;
    private javax.swing.JLabel TotalPrice;
    private javax.swing.JLabel TourismTax;
    private javax.swing.JButton backReceipt;
    private javax.swing.JLabel checkInDateReceipt;
    private javax.swing.JLabel checkInDateReceipt3;
    private javax.swing.JLabel checkOutDateReceipt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel todayDate;
    private javax.swing.JLabel userContact;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
